name: CE9010_2018
channels:
- conda-forge
- defaults
dependencies:
# basic
- git
- python
- numpy
- scipy
- pandas
- matplotlib
- scikit-learn
- networkx
- ipython
- jupyter
- jupyterlab_launcher=0.5.0
# additional
- seaborn
- tweepy
- requests
- tqdm
- statsmodels
- librosa
- ffmpeg
- sympy
- sqlalchemy
- xlrd
- requests
# deep learning
- tensorflow
- keras

